# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Tarifsimulation.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Tarifsimulation_View(object):
    def setupUi(self, Form, name:str):
        Form.setObjectName(name)
        Form.resize(1395, 907)
        self.scroll_area_tarifsimulation = QtWidgets.QScrollArea(Form)
        self.scroll_area_tarifsimulation.setGeometry(QtCore.QRect(70, 70, 1254, 600))
        self.scroll_area_tarifsimulation.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scroll_area_tarifsimulation.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scroll_area_tarifsimulation.setWidgetResizable(True)
        self.scroll_area_tarifsimulation.setObjectName("scroll_area_tarifsimulation")
        self.scroll_area_trifsimulation_Contents = QtWidgets.QWidget()
        self.scroll_area_trifsimulation_Contents.setGeometry(QtCore.QRect(70, 70, 1237, 1494))
        self.scroll_area_trifsimulation_Contents.setObjectName("scroll_area_trifsimulation_Contents")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.scroll_area_trifsimulation_Contents)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tarifsimulation_bottom = QtWidgets.QFrame(self.scroll_area_trifsimulation_Contents)
        self.tarifsimulation_bottom.setMinimumSize(QtCore.QSize(0, 0))
        self.tarifsimulation_bottom.setObjectName("tarifsimulation_bottom")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tarifsimulation_bottom)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame_ts_container1 = QtWidgets.QFrame(self.tarifsimulation_bottom)
        self.frame_ts_container1.setStyleSheet("background-color: white;\n"
"border-radius: 20%;")
        self.frame_ts_container1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_ts_container1.setObjectName("frame_ts_container1")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_ts_container1)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.frame_button_3 = QtWidgets.QFrame(self.frame_ts_container1)
        self.frame_button_3.setMaximumSize(QtCore.QSize(150, 16777215))
        self.frame_button_3.setObjectName("frame_button_3")
        self.verticalLayout_43 = QtWidgets.QVBoxLayout(self.frame_button_3)
        self.verticalLayout_43.setObjectName("verticalLayout_43")
        spacerItem = QtWidgets.QSpacerItem(20, 150, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_43.addItem(spacerItem)
        self.pushButton_tarifsimulation_excel_statistik = QtWidgets.QPushButton(self.frame_button_3)
        self.pushButton_tarifsimulation_excel_statistik.setMinimumSize(QtCore.QSize(140, 0))
        self.pushButton_tarifsimulation_excel_statistik.setMaximumSize(QtCore.QSize(140, 16777215))
        self.pushButton_tarifsimulation_excel_statistik.setStyleSheet("QPushButton {\n"
"    border-left: 8px solid;\n"
"    border-color: rgb(1,115,164);\n"
"    background-color: rgb(1,115,164);   \n"
"    text-align: center;\n"
"    color: rgb(255,255,255);\n"
"    padding: 8px;\n"
"    padding-left: 30 px;\n"
"    padding-right: 15 px;\n"
"    border-radius: 5px;\n"
"    background-image: url(:/16x16/icons/16x16/cil-external-link.png);\n"
"    background-position: left;\n"
"    background-repeat: no-reperat;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(1,133,177);\n"
"    border-color: rgb(1,133,177);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(1,115,164);\n"
"    border-color: rgb(1,115,164);\n"
"}")
        self.pushButton_tarifsimulation_excel_statistik.setObjectName("pushButton_tarifsimulation_excel_statistik")
        self.verticalLayout_43.addWidget(self.pushButton_tarifsimulation_excel_statistik)
        self.pushButton_tarifsimulation_sichern_statistik = QtWidgets.QPushButton(self.frame_button_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(150)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_tarifsimulation_sichern_statistik.sizePolicy().hasHeightForWidth())
        self.pushButton_tarifsimulation_sichern_statistik.setSizePolicy(sizePolicy)
        self.pushButton_tarifsimulation_sichern_statistik.setMinimumSize(QtCore.QSize(140, 0))
        self.pushButton_tarifsimulation_sichern_statistik.setMaximumSize(QtCore.QSize(140, 16777215))
        self.pushButton_tarifsimulation_sichern_statistik.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_tarifsimulation_sichern_statistik.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_tarifsimulation_sichern_statistik.setStyleSheet("QPushButton {\n"
"    border-left: 8px solid;\n"
"    border-color: rgb(1,115,164);\n"
"    background-color: rgb(1,115,164);   \n"
"    text-align: center;\n"
"    color: rgb(255,255,255);\n"
"    padding: 8px;\n"
"    padding-left: 20 px;\n"
"    padding-right: 15 px;\n"
"    border-radius: 5px;\n"
"    background-image: url(:/16x16/icons/16x16/cil-save.png);\n"
"    background-position: left;\n"
"    background-repeat: no-reperat;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(1,133,177);\n"
"    border-color: rgb(1,133,177);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(1,115,164);\n"
"    border-color: rgb(1,115,164);\n"
"}")
        self.pushButton_tarifsimulation_sichern_statistik.setObjectName("pushButton_tarifsimulation_sichern_statistik")
        self.verticalLayout_43.addWidget(self.pushButton_tarifsimulation_sichern_statistik)
        spacerItem1 = QtWidgets.QSpacerItem(20, 150, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_43.addItem(spacerItem1)
        self.horizontalLayout_16.addWidget(self.frame_button_3)
        self.widget_ts_statistik = QtWidgets.QWidget(self.frame_ts_container1)
        self.widget_ts_statistik.setMinimumSize(QtCore.QSize(0, 400))
        self.widget_ts_statistik.setObjectName("widget_ts_statistik")
        self.horizontalLayout_16.addWidget(self.widget_ts_statistik)
        self.gridLayout_5.addWidget(self.frame_ts_container1, 0, 0, 1, 2)
        self.frame_ts_container2 = QtWidgets.QFrame(self.tarifsimulation_bottom)
        self.frame_ts_container2.setStyleSheet("background-color: white;\n"
"border-radius: 20%;")
        self.frame_ts_container2.setObjectName("frame_ts_container2")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.frame_ts_container2)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.frame_button_4 = QtWidgets.QFrame(self.frame_ts_container2)
        self.frame_button_4.setMaximumSize(QtCore.QSize(150, 16777215))
        self.frame_button_4.setObjectName("frame_button_4")
        self.verticalLayout_44 = QtWidgets.QVBoxLayout(self.frame_button_4)
        self.verticalLayout_44.setObjectName("verticalLayout_44")
        spacerItem2 = QtWidgets.QSpacerItem(20, 150, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_44.addItem(spacerItem2)
        self.pushButton_tarifsimulation_excel_verbrauch = QtWidgets.QPushButton(self.frame_button_4)
        self.pushButton_tarifsimulation_excel_verbrauch.setMinimumSize(QtCore.QSize(140, 0))
        self.pushButton_tarifsimulation_excel_verbrauch.setMaximumSize(QtCore.QSize(140, 16777215))
        self.pushButton_tarifsimulation_excel_verbrauch.setStyleSheet("QPushButton {\n"
"    border-left: 8px solid;\n"
"    border-color: rgb(1,115,164);\n"
"    background-color: rgb(1,115,164);   \n"
"    text-align: center;\n"
"    color: rgb(255,255,255);\n"
"    padding: 8px;\n"
"    padding-left: 30 px;\n"
"    padding-right: 15 px;\n"
"    border-radius: 5px;\n"
"    background-image: url(:/16x16/icons/16x16/cil-external-link.png);\n"
"    background-position: left;\n"
"    background-repeat: no-reperat;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(1,133,177);\n"
"    border-color: rgb(1,133,177);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(1,115,164);\n"
"    border-color: rgb(1,115,164);\n"
"}")
        self.pushButton_tarifsimulation_excel_verbrauch.setObjectName("pushButton_tarifsimulation_excel_verbrauch")
        self.verticalLayout_44.addWidget(self.pushButton_tarifsimulation_excel_verbrauch)
        self.pushButton_tarifsimulation_sichern_verbrauch = QtWidgets.QPushButton(self.frame_button_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(150)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_tarifsimulation_sichern_verbrauch.sizePolicy().hasHeightForWidth())
        self.pushButton_tarifsimulation_sichern_verbrauch.setSizePolicy(sizePolicy)
        self.pushButton_tarifsimulation_sichern_verbrauch.setMinimumSize(QtCore.QSize(140, 0))
        self.pushButton_tarifsimulation_sichern_verbrauch.setMaximumSize(QtCore.QSize(140, 16777215))
        self.pushButton_tarifsimulation_sichern_verbrauch.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_tarifsimulation_sichern_verbrauch.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_tarifsimulation_sichern_verbrauch.setStyleSheet("QPushButton {\n"
"    border-left: 8px solid;\n"
"    border-color: rgb(1,115,164);\n"
"    background-color: rgb(1,115,164);   \n"
"    text-align: center;\n"
"    color: rgb(255,255,255);\n"
"    padding: 8px;\n"
"    padding-left: 20 px;\n"
"    padding-right: 15 px;\n"
"    border-radius: 5px;\n"
"    background-image: url(:/16x16/icons/16x16/cil-save.png);\n"
"    background-position: left;\n"
"    background-repeat: no-reperat;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(1,133,177);\n"
"    border-color: rgb(1,133,177);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(1,115,164);\n"
"    border-color: rgb(1,115,164);\n"
"}")
        self.pushButton_tarifsimulation_sichern_verbrauch.setObjectName("pushButton_tarifsimulation_sichern_verbrauch")
        self.verticalLayout_44.addWidget(self.pushButton_tarifsimulation_sichern_verbrauch)
        spacerItem3 = QtWidgets.QSpacerItem(20, 150, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_44.addItem(spacerItem3)
        self.horizontalLayout_17.addWidget(self.frame_button_4)
        self.widget_ts_verbrauch = QtWidgets.QWidget(self.frame_ts_container2)
        self.widget_ts_verbrauch.setMinimumSize(QtCore.QSize(0, 400))
        self.widget_ts_verbrauch.setObjectName("widget_ts_verbrauch")
        self.horizontalLayout_17.addWidget(self.widget_ts_verbrauch)
        self.gridLayout_5.addWidget(self.frame_ts_container2, 2, 0, 1, 2)
        self.gridLayout_4.addWidget(self.tarifsimulation_bottom, 3, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.scroll_area_trifsimulation_Contents)
        self.line.setWindowModality(QtCore.Qt.NonModal)
        self.line.setMinimumSize(QtCore.QSize(0, 0))
        self.line.setMaximumSize(QtCore.QSize(300000, 1))
        font = QtGui.QFont()
        font.setPointSize(2)
        self.line.setFont(font)
        self.line.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.line.setStyleSheet("background: rgb(59,56,56);\n"
"")
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setLineWidth(0)
        self.line.setMidLineWidth(0)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.gridLayout_4.addWidget(self.line, 2, 0, 1, 1)
        self.tarifsimulation_center = QtWidgets.QFrame(self.scroll_area_trifsimulation_Contents)
        self.tarifsimulation_center.setObjectName("tarifsimulation_center")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.tarifsimulation_center)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.btn_ts_simulieren = QtWidgets.QPushButton(self.tarifsimulation_center)
        self.btn_ts_simulieren.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_ts_simulieren.sizePolicy().hasHeightForWidth())
        self.btn_ts_simulieren.setSizePolicy(sizePolicy)
        self.btn_ts_simulieren.setMaximumSize(QtCore.QSize(100, 24))
        self.btn_ts_simulieren.setSizeIncrement(QtCore.QSize(0, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(1, 115, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(1, 115, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(1, 115, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(1, 115, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(1, 115, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(1, 115, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(1, 115, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(1, 115, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(1, 115, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.btn_ts_simulieren.setPalette(palette)
        self.btn_ts_simulieren.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: rgb(1,115,164);   \n"
"    text-align: center;\n"
"    color: rgb(255,255,255);\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(1,133,177);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(1,115,164);\n"
"}")
        self.btn_ts_simulieren.setIconSize(QtCore.QSize(16, 16))
        self.btn_ts_simulieren.setFlat(False)
        self.btn_ts_simulieren.setObjectName("btn_ts_simulieren")
        self.gridLayout_16.addWidget(self.btn_ts_simulieren, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.tarifsimulation_center, 1, 0, 1, 1)
        self.tarifsimulation_top = QtWidgets.QFrame(self.scroll_area_trifsimulation_Contents)
        self.tarifsimulation_top.setMinimumSize(QtCore.QSize(0, 450))
        self.tarifsimulation_top.setMaximumSize(QtCore.QSize(16777215, 500))
        self.tarifsimulation_top.setObjectName("tarifsimulation_top")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.tarifsimulation_top)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.frame_tarifauswahl = QtWidgets.QFrame(self.tarifsimulation_top)
        self.frame_tarifauswahl.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_tarifauswahl.setMaximumSize(QtCore.QSize(400, 16777215))
        self.frame_tarifauswahl.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_tarifauswahl.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_tarifauswahl.setObjectName("frame_tarifauswahl")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_tarifauswahl)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.spinBox_ts_arbeitspreis_2 = QtWidgets.QDoubleSpinBox(self.frame_tarifauswahl)
        self.spinBox_ts_arbeitspreis_2.setMinimumSize(QtCore.QSize(100, 30))
        self.spinBox_ts_arbeitspreis_2.setMaximumSize(QtCore.QSize(100, 30))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(59, 56, 56))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(59, 56, 56))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(59, 56, 56))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(59, 56, 56))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(59, 56, 56))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(59, 56, 56))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(59, 56, 56))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(59, 56, 56))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(59, 56, 56))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.spinBox_ts_arbeitspreis_2.setPalette(palette)
        font = QtGui.QFont()
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.spinBox_ts_arbeitspreis_2.setFont(font)
        self.spinBox_ts_arbeitspreis_2.setStyleSheet("QDoubleSpinBox{\n"
"    color: rgb(59,56,56);\n"
"    border: 1px solid;\n"
"    border-color:  rgb(1,115,164);\n"
"    border-radius: 5px;\n"
"}")
        self.spinBox_ts_arbeitspreis_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_ts_arbeitspreis_2.setDecimals(4)
        self.spinBox_ts_arbeitspreis_2.setMaximum(999999.99)
        self.spinBox_ts_arbeitspreis_2.setObjectName("spinBox_ts_arbeitspreis_2")
        self.gridLayout_8.addWidget(self.spinBox_ts_arbeitspreis_2, 4, 1, 1, 1)
        self.label_ts_grundpreis_2 = QtWidgets.QLabel(self.frame_tarifauswahl)
        self.label_ts_grundpreis_2.setMaximumSize(QtCore.QSize(135, 16777215))
        self.label_ts_grundpreis_2.setObjectName("label_ts_grundpreis_2")
        self.gridLayout_8.addWidget(self.label_ts_grundpreis_2, 5, 0, 1, 1)
        self.spinBox_ts_grundpreis_2 = QtWidgets.QDoubleSpinBox(self.frame_tarifauswahl)
        self.spinBox_ts_grundpreis_2.setMinimumSize(QtCore.QSize(100, 30))
        self.spinBox_ts_grundpreis_2.setMaximumSize(QtCore.QSize(100, 30))
        self.spinBox_ts_grundpreis_2.setStyleSheet("QDoubleSpinBox{\n"
"    color: rgb(59,56,56);\n"
"    border: 1px solid;\n"
"    border-color: rgb(1,115,164);\n"
"    border-radius: 5px;\n"
"}")
        self.spinBox_ts_grundpreis_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_ts_grundpreis_2.setDecimals(2)
        self.spinBox_ts_grundpreis_2.setMaximum(999999.99)
        self.spinBox_ts_grundpreis_2.setObjectName("spinBox_ts_grundpreis_2")
        self.gridLayout_8.addWidget(self.spinBox_ts_grundpreis_2, 5, 1, 1, 1)
        self.label_ts_tarifauswahl_2 = QtWidgets.QLabel(self.frame_tarifauswahl)
        self.label_ts_tarifauswahl_2.setMinimumSize(QtCore.QSize(0, 0))
        self.label_ts_tarifauswahl_2.setMaximumSize(QtCore.QSize(135, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_ts_tarifauswahl_2.setPalette(palette)
        self.label_ts_tarifauswahl_2.setObjectName("label_ts_tarifauswahl_2")
        self.gridLayout_8.addWidget(self.label_ts_tarifauswahl_2, 0, 0, 1, 1)
        self.label_ts_indexauswahl_2 = QtWidgets.QLabel(self.frame_tarifauswahl)
        self.label_ts_indexauswahl_2.setMinimumSize(QtCore.QSize(0, 0))
        self.label_ts_indexauswahl_2.setMaximumSize(QtCore.QSize(135, 16777215))
        self.label_ts_indexauswahl_2.setStyleSheet("    color: rgb(59,56,56);")
        self.label_ts_indexauswahl_2.setObjectName("label_ts_indexauswahl_2")
        self.gridLayout_8.addWidget(self.label_ts_indexauswahl_2, 1, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_8.addItem(spacerItem4, 2, 0, 1, 1)
        self.label_ts_arbeitspreis_2 = QtWidgets.QLabel(self.frame_tarifauswahl)
        self.label_ts_arbeitspreis_2.setMaximumSize(QtCore.QSize(135, 16777215))
        self.label_ts_arbeitspreis_2.setObjectName("label_ts_arbeitspreis_2")
        self.gridLayout_8.addWidget(self.label_ts_arbeitspreis_2, 4, 0, 1, 1)
        self.comboBox_ts_tarifauswahl = QtWidgets.QComboBox(self.frame_tarifauswahl)
        self.comboBox_ts_tarifauswahl.setMinimumSize(QtCore.QSize(150, 30))
        self.comboBox_ts_tarifauswahl.setMaximumSize(QtCore.QSize(300, 30))
        self.comboBox_ts_tarifauswahl.setStyleSheet("QComboBox {\n"
"    background-position: left;\n"
"    border-color: rgb(1,115,164);\n"
"    color: rgb(59,56,56);\n"
"}\n"
"QListView {\n"
"    background-color: white;\n"
"    color: rgb(59,56,56);\n"
"}\n"
"")
        self.comboBox_ts_tarifauswahl.setObjectName("comboBox_ts_tarifauswahl")
        self.gridLayout_8.addWidget(self.comboBox_ts_tarifauswahl, 0, 1, 1, 1)
        self.comboBox_ts_indexauswahl_2 = QtWidgets.QComboBox(self.frame_tarifauswahl)
        self.comboBox_ts_indexauswahl_2.setMinimumSize(QtCore.QSize(150, 30))
        self.comboBox_ts_indexauswahl_2.setMaximumSize(QtCore.QSize(300, 30))
        self.comboBox_ts_indexauswahl_2.setSizeIncrement(QtCore.QSize(300, 0))
        self.comboBox_ts_indexauswahl_2.setStyleSheet("QComboBox {\n"
"    background-position: left;\n"
"    border-color: rgb(1,115,164);\n"
"    color: rgb(59,56,56);\n"
"}\n"
"QListView {\n"
"    background-color: white;\n"
"    color: rgb(59,56,56);\n"
"}\n"
"")
        self.comboBox_ts_indexauswahl_2.setObjectName("comboBox_ts_indexauswahl_2")
        self.gridLayout_8.addWidget(self.comboBox_ts_indexauswahl_2, 1, 1, 1, 1)
        self.label_ts_verbrauch_2 = QtWidgets.QLabel(self.frame_tarifauswahl)
        self.label_ts_verbrauch_2.setMaximumSize(QtCore.QSize(135, 16777215))
        self.label_ts_verbrauch_2.setObjectName("label_ts_verbrauch_2")
        self.gridLayout_8.addWidget(self.label_ts_verbrauch_2, 6, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem5, 7, 0, 1, 1)
        self.spinBox_ts_verbrauch_2 = QtWidgets.QSpinBox(self.frame_tarifauswahl)
        self.spinBox_ts_verbrauch_2.setMinimumSize(QtCore.QSize(100, 30))
        self.spinBox_ts_verbrauch_2.setMaximumSize(QtCore.QSize(100, 30))
        self.spinBox_ts_verbrauch_2.setStyleSheet("QSpinBox{\n"
"    color: rgb(59,56,56);\n"
"    border: 1px solid;\n"
"    border-color:  rgb(1,115,164);\n"
"    border-radius: 5px;\n"
"}")
        self.spinBox_ts_verbrauch_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_ts_verbrauch_2.setMaximum(999999)
        self.spinBox_ts_verbrauch_2.setObjectName("spinBox_ts_verbrauch_2")
        self.gridLayout_8.addWidget(self.spinBox_ts_verbrauch_2, 6, 1, 1, 1)
        self.horizontalLayout_15.addWidget(self.frame_tarifauswahl)
        self.verticalFrame = QtWidgets.QFrame(self.tarifsimulation_top)
        self.verticalFrame.setMinimumSize(QtCore.QSize(200, 0))
        self.verticalFrame.setMaximumSize(QtCore.QSize(250, 16777215))
        self.verticalFrame.setObjectName("verticalFrame")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.verticalFrame)
        self.verticalLayout_18.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.frame_graph1 = QtWidgets.QFrame(self.verticalFrame)
        self.frame_graph1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_graph1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_graph1.setObjectName("frame_graph1")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.frame_graph1)
        self.gridLayout_20.setContentsMargins(-1, 0, -1, 9)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.dateEdit_ts_ende_3 = QtWidgets.QDateEdit(self.frame_graph1)
        self.dateEdit_ts_ende_3.setMinimumSize(QtCore.QSize(60, 30))
        self.dateEdit_ts_ende_3.setMaximumSize(QtCore.QSize(80, 16777215))
        self.dateEdit_ts_ende_3.setStyleSheet("QDateEdit{\n"
"    color: rgb(59,56,56);\n"
"    border: 1px solid;\n"
"    border-color:  rgb(1,115,164);\n"
"    border-radius: 5px;\n"
"}")
        self.dateEdit_ts_ende_3.setDateTime(QtCore.QDateTime(QtCore.QDate(2021, 12, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit_ts_ende_3.setDate(QtCore.QDate(2021, 12, 1))
        self.dateEdit_ts_ende_3.setObjectName("dateEdit_ts_ende_3")
        self.gridLayout_20.addWidget(self.dateEdit_ts_ende_3, 2, 1, 1, 2)
        self.label_ts_datum_ende_1 = QtWidgets.QLabel(self.frame_graph1)
        self.label_ts_datum_ende_1.setObjectName("label_ts_datum_ende_1")
        self.gridLayout_20.addWidget(self.label_ts_datum_ende_1, 2, 0, 1, 1)
        self.label_placeholder = QtWidgets.QLabel(self.frame_graph1)
        self.label_placeholder.setMinimumSize(QtCore.QSize(0, 20))
        self.label_placeholder.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_placeholder.setText("")
        self.label_placeholder.setObjectName("label_placeholder")
        self.gridLayout_20.addWidget(self.label_placeholder, 3, 0, 1, 1)
        self.label_ts_datum_anfang_1 = QtWidgets.QLabel(self.frame_graph1)
        self.label_ts_datum_anfang_1.setObjectName("label_ts_datum_anfang_1")
        self.gridLayout_20.addWidget(self.label_ts_datum_anfang_1, 1, 0, 1, 1)
        self.dateEdit_ts_anfang_3 = QtWidgets.QDateEdit(self.frame_graph1)
        self.dateEdit_ts_anfang_3.setMinimumSize(QtCore.QSize(60, 30))
        self.dateEdit_ts_anfang_3.setMaximumSize(QtCore.QSize(80, 16777215))
        self.dateEdit_ts_anfang_3.setStyleSheet("QDateEdit{\n"
"    color: rgb(59,56,56);\n"
"    border: 1px solid;\n"
"    border-color:  rgb(1,115,164);\n"
"    border-radius: 5px;\n"
"}")
        self.dateEdit_ts_anfang_3.setDate(QtCore.QDate(2010, 1, 1))
        self.dateEdit_ts_anfang_3.setObjectName("dateEdit_ts_anfang_3")
        self.gridLayout_20.addWidget(self.dateEdit_ts_anfang_3, 1, 1, 1, 2)
        self.label_ts_graph_date = QtWidgets.QLabel(self.frame_graph1)
        self.label_ts_graph_date.setStyleSheet("color: rgb(0,0,90);\n"
"font: bold;")
        self.label_ts_graph_date.setObjectName("label_ts_graph_date")
        self.gridLayout_20.addWidget(self.label_ts_graph_date, 0, 0, 1, 2)
        self.verticalLayout_18.addWidget(self.frame_graph1)
        self.frame_list1 = QtWidgets.QFrame(self.verticalFrame)
        self.frame_list1.setMinimumSize(QtCore.QSize(0, 250))
        self.frame_list1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_list1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_list1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_list1.setObjectName("frame_list1")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.frame_list1)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.checkBox_BP = QtWidgets.QCheckBox(self.frame_list1)
        self.checkBox_BP.setStyleSheet("QCheckBox{\n"
"    color: rgb(59,56,56);\n"
"}")
        self.checkBox_BP.setObjectName("checkBox_BP")
        self.gridLayout_17.addWidget(self.checkBox_BP, 0, 0, 1, 1)
        self.checkBox_KP = QtWidgets.QCheckBox(self.frame_list1)
        self.checkBox_KP.setStyleSheet("QCheckBox{\n"
"    color: rgb(59,56,56);\n"
"}")
        self.checkBox_KP.setObjectName("checkBox_KP")
        self.gridLayout_17.addWidget(self.checkBox_KP, 1, 0, 1, 1)
        self.checkBox_MJE = QtWidgets.QCheckBox(self.frame_list1)
        self.checkBox_MJE.setStyleSheet("QCheckBox{\n"
"    color: rgb(59,56,56);\n"
"}")
        self.checkBox_MJE.setObjectName("checkBox_MJE")
        self.gridLayout_17.addWidget(self.checkBox_MJE, 2, 0, 1, 1)
        self.checkBox_MJP = QtWidgets.QCheckBox(self.frame_list1)
        self.checkBox_MJP.setStyleSheet("QCheckBox{\n"
"    color: rgb(59,56,56);\n"
"}")
        self.checkBox_MJP.setObjectName("checkBox_MJP")
        self.gridLayout_17.addWidget(self.checkBox_MJP, 3, 0, 1, 1)
        self.checkBox_KJ = QtWidgets.QCheckBox(self.frame_list1)
        self.checkBox_KJ.setStyleSheet("QCheckBox{\n"
"    color: rgb(59,56,56);\n"
"}")
        self.checkBox_KJ.setObjectName("checkBox_KJ")
        self.gridLayout_17.addWidget(self.checkBox_KJ, 4, 0, 1, 1)
        self.checkBox_EJ = QtWidgets.QCheckBox(self.frame_list1)
        self.checkBox_EJ.setStyleSheet("QCheckBox{\n"
"    color: rgb(59,56,56);\n"
"}")
        self.checkBox_EJ.setObjectName("checkBox_EJ")
        self.gridLayout_17.addWidget(self.checkBox_EJ, 5, 0, 1, 1)
        self.verticalLayout_18.addWidget(self.frame_list1)
        self.horizontalLayout_15.addWidget(self.verticalFrame)
        self.verticalFrame_2 = QtWidgets.QFrame(self.tarifsimulation_top)
        self.verticalFrame_2.setMinimumSize(QtCore.QSize(200, 0))
        self.verticalFrame_2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.verticalFrame_2.setObjectName("verticalFrame_2")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.verticalFrame_2)
        self.verticalLayout_27.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.frame_graph2 = QtWidgets.QFrame(self.verticalFrame_2)
        self.frame_graph2.setEnabled(True)
        self.frame_graph2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_graph2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_graph2.setObjectName("frame_graph2")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.frame_graph2)
        self.gridLayout_11.setContentsMargins(-1, 0, -1, 9)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.dateEdit_ts_index_2 = QtWidgets.QDateEdit(self.frame_graph2)
        self.dateEdit_ts_index_2.setMinimumSize(QtCore.QSize(60, 30))
        self.dateEdit_ts_index_2.setMaximumSize(QtCore.QSize(80, 16777215))
        self.dateEdit_ts_index_2.setStyleSheet("QDateEdit{\n"
"    color: rgb(59,56,56);\n"
"    border: 1px solid;\n"
"    border-color: rgb(1,115,164);\n"
"    border-radius: 5px;\n"
"}")
        self.dateEdit_ts_index_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.dateEdit_ts_index_2.setDateTime(QtCore.QDateTime(QtCore.QDate(2021, 12, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit_ts_index_2.setDate(QtCore.QDate(2021, 12, 1))
        self.dateEdit_ts_index_2.setObjectName("dateEdit_ts_index_2")
        self.gridLayout_11.addWidget(self.dateEdit_ts_index_2, 3, 1, 1, 1)
        self.label_ts_datum_ende_4 = QtWidgets.QLabel(self.frame_graph2)
        self.label_ts_datum_ende_4.setObjectName("label_ts_datum_ende_4")
        self.gridLayout_11.addWidget(self.label_ts_datum_ende_4, 2, 0, 1, 1)
        self.label_tarifvergleich_index_3 = QtWidgets.QLabel(self.frame_graph2)
        self.label_tarifvergleich_index_3.setStyleSheet("color: rgb(59, 56, 56);")
        self.label_tarifvergleich_index_3.setObjectName("label_tarifvergleich_index_3")
        self.gridLayout_11.addWidget(self.label_tarifvergleich_index_3, 3, 0, 1, 1)
        self.label_ts_datum_anfang_4 = QtWidgets.QLabel(self.frame_graph2)
        self.label_ts_datum_anfang_4.setObjectName("label_ts_datum_anfang_4")
        self.gridLayout_11.addWidget(self.label_ts_datum_anfang_4, 1, 0, 1, 1)
        self.spinBox_ts_consumption_anfang_3 = QtWidgets.QSpinBox(self.frame_graph2)
        self.spinBox_ts_consumption_anfang_3.setMinimumSize(QtCore.QSize(60, 30))
        self.spinBox_ts_consumption_anfang_3.setMaximumSize(QtCore.QSize(80, 16777215))
        self.spinBox_ts_consumption_anfang_3.setStyleSheet("QSpinBox{\n"
"    color: rgb(59,56,56);\n"
"    border: 1px solid;\n"
"    border-color:  rgb(1,115,164);\n"
"    border-radius: 5px;\n"
"}\n"
"")
        self.spinBox_ts_consumption_anfang_3.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_ts_consumption_anfang_3.setMinimum(1)
        self.spinBox_ts_consumption_anfang_3.setMaximum(999999)
        self.spinBox_ts_consumption_anfang_3.setObjectName("spinBox_ts_consumption_anfang_3")
        self.gridLayout_11.addWidget(self.spinBox_ts_consumption_anfang_3, 1, 1, 1, 1)
        self.spinBox_ts_consumption_ende_3 = QtWidgets.QSpinBox(self.frame_graph2)
        self.spinBox_ts_consumption_ende_3.setMinimumSize(QtCore.QSize(60, 30))
        self.spinBox_ts_consumption_ende_3.setMaximumSize(QtCore.QSize(80, 16777215))
        self.spinBox_ts_consumption_ende_3.setStyleSheet("QSpinBox{\n"
"    color: rgb(59,56,56);\n"
"    border: 1px solid;\n"
"    border-color:  rgb(1,115,164);\n"
"    border-radius: 5px;\n"
"}")
        self.spinBox_ts_consumption_ende_3.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_ts_consumption_ende_3.setMaximum(999999)
        self.spinBox_ts_consumption_ende_3.setProperty("value", 3000)
        self.spinBox_ts_consumption_ende_3.setObjectName("spinBox_ts_consumption_ende_3")
        self.gridLayout_11.addWidget(self.spinBox_ts_consumption_ende_3, 2, 1, 1, 1)
        self.label_ts_graph_consumption_3 = QtWidgets.QLabel(self.frame_graph2)
        self.label_ts_graph_consumption_3.setStyleSheet("color: rgb(0,0,90);\n"
"font: bold;")
        self.label_ts_graph_consumption_3.setObjectName("label_ts_graph_consumption_3")
        self.gridLayout_11.addWidget(self.label_ts_graph_consumption_3, 0, 0, 1, 2)
        self.verticalLayout_27.addWidget(self.frame_graph2)
        self.frame_list2 = QtWidgets.QFrame(self.verticalFrame_2)
        self.frame_list2.setMinimumSize(QtCore.QSize(0, 250))
        self.frame_list2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_list2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_list2.setObjectName("frame_list2")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.frame_list2)
        self.verticalLayout_21.setContentsMargins(-1, -1, -1, 82)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.checkBox_AM = QtWidgets.QCheckBox(self.frame_list2)
        self.checkBox_AM.setStyleSheet("QCheckBox{\n"
"    color: rgb(59,56,56);\n"
"}")
        self.checkBox_AM.setObjectName("checkBox_AM")
        self.verticalLayout_21.addWidget(self.checkBox_AM)
        self.checkBox_RM = QtWidgets.QCheckBox(self.frame_list2)
        self.checkBox_RM.setStyleSheet("QCheckBox{\n"
"    color: rgb(59,56,56);\n"
"}")
        self.checkBox_RM.setObjectName("checkBox_RM")
        self.verticalLayout_21.addWidget(self.checkBox_RM)
        self.checkBox_BK = QtWidgets.QCheckBox(self.frame_list2)
        self.checkBox_BK.setStyleSheet("QCheckBox{\n"
"    color: rgb(59,56,56);\n"
"}")
        self.checkBox_BK.setObjectName("checkBox_BK")
        self.verticalLayout_21.addWidget(self.checkBox_BK)
        self.checkBox_E = QtWidgets.QCheckBox(self.frame_list2)
        self.checkBox_E.setStyleSheet("QCheckBox{\n"
"    color: rgb(59,56,56);\n"
"}")
        self.checkBox_E.setObjectName("checkBox_E")
        self.verticalLayout_21.addWidget(self.checkBox_E)
        self.verticalLayout_27.addWidget(self.frame_list2)
        self.horizontalLayout_15.addWidget(self.verticalFrame_2)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem6)
        self.gridLayout_4.addWidget(self.tarifsimulation_top, 0, 0, 1, 1)
        self.frame_ts_details_window_2 = QtWidgets.QFrame(self.scroll_area_trifsimulation_Contents)
        self.frame_ts_details_window_2.setMinimumSize(QtCore.QSize(0, 100))
        self.frame_ts_details_window_2.setStyleSheet("background-color: rgb(225, 225, 225);\n"
"border-radius: 10px;")
        self.frame_ts_details_window_2.setObjectName("frame_ts_details_window_2")
        self.gridLayout_31 = QtWidgets.QGridLayout(self.frame_ts_details_window_2)
        self.gridLayout_31.setObjectName("gridLayout_31")
        self.label_ts_details = QtWidgets.QLabel(self.frame_ts_details_window_2)
        self.label_ts_details.setText("")
        self.label_ts_details.setObjectName("label_ts_details")
        self.gridLayout_31.addWidget(self.label_ts_details, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame_ts_details_window_2, 4, 0, 1, 1)
        self.scroll_area_tarifsimulation.setWidget(self.scroll_area_trifsimulation_Contents)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_tarifsimulation_excel_statistik.setText(_translate("Form", "Excel exportieren"))
        self.pushButton_tarifsimulation_sichern_statistik.setText(_translate("Form", "Grafik speichern"))
        self.pushButton_tarifsimulation_excel_verbrauch.setText(_translate("Form", "Excel exportieren"))
        self.pushButton_tarifsimulation_sichern_verbrauch.setText(_translate("Form", "Grafik speichern"))
        self.btn_ts_simulieren.setText(_translate("Form", "simulieren"))
        self.label_ts_grundpreis_2.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#3b3838;\">Grundpreis         [Eur/Jahr]</span></p></body></html>"))
        self.label_ts_tarifauswahl_2.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#3b3838;\">Tarifauswahl</span></p></body></html>"))
        self.label_ts_indexauswahl_2.setText(_translate("Form", "Indexauwahl"))
        self.label_ts_arbeitspreis_2.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#3b3838;\">Arbeitspreis_p0 [Cent/kWh]</span></p></body></html>"))
        self.label_ts_verbrauch_2.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#3b3838;\">Verbrauch [kWh/Jahr]</span></p></body></html>"))
        self.dateEdit_ts_ende_3.setDisplayFormat(_translate("Form", "MM.yyyy"))
        self.label_ts_datum_ende_1.setText(_translate("Form", "Bis"))
        self.label_ts_datum_anfang_1.setText(_translate("Form", "Von:"))
        self.dateEdit_ts_anfang_3.setDisplayFormat(_translate("Form", "MM.yyyy"))
        self.label_ts_graph_date.setText(_translate("Form", "1. Grafik Datum"))
        self.checkBox_BP.setText(_translate("Form", "Beschaffungspreis [cts/kWh]"))
        self.checkBox_KP.setText(_translate("Form", "Energiepreis Kunde [cts/kWh]"))
        self.checkBox_MJE.setText(_translate("Form", "Marge Jahr [EUR]"))
        self.checkBox_MJP.setText(_translate("Form", "Marge Jahr [%]"))
        self.checkBox_KJ.setText(_translate("Form", "Kosten Jahr [EUR]"))
        self.checkBox_EJ.setText(_translate("Form", "Erlöse Jahr [EUR]"))
        self.dateEdit_ts_index_2.setDisplayFormat(_translate("Form", "MM.yyyy"))
        self.label_ts_datum_ende_4.setText(_translate("Form", "Bis"))
        self.label_tarifvergleich_index_3.setText(_translate("Form", "Index:"))
        self.label_ts_datum_anfang_4.setText(_translate("Form", "Von:"))
        self.label_ts_graph_consumption_3.setText(_translate("Form", "2. Grafik Verbrauch"))
        self.checkBox_AM.setText(_translate("Form", "absolute Marge"))
        self.checkBox_RM.setText(_translate("Form", "relative Marge"))
        self.checkBox_BK.setText(_translate("Form", "Beschaffungskosten"))
        self.checkBox_E.setText(_translate("Form", "Erlöse"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
